name: Hello
on: push
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world sekai"
      - run: echo "Hello Second line"
      - run: echo ${{ runner.os }}
      - run: echo ${{ runner.arch }}
      - uses: actions/checkout@v4
