name: Hello
on: push
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello world sekai"
          echo "Hello Second line"
          echo ${{ runner.os }}
          echo ${{ runner.arch }}
      - uses: actions/checkout@v4
